require: rubocop-rspec

AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*.rb

Rails:
  Enabled: true

LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 28

SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Documentation: # format too restricted
  Enabled: false

Style/FileName:
  Exclude:
    - 'Gemfile'

Bundler/OrderedGems:
  Enabled: false
